import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SvgSearch } from '@/components/icons/search'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} mx-auto max-w-[1068px] px-4`}>
        <header className=' mb-5 mt-9 flex min-h-11 w-full  flex-col items-center justify-start gap-5 py-2 min-[400px]:flex-row'>
          <h1 className='text-xl font-extrabold'>maristore</h1>
          <label className='flex max-w-80 items-center justify-center gap-3 rounded-3xl bg-zinc-900 px-5 py-3'>
            <SvgSearch />
            <input
              type='text'
              name=''
              id=''
              className='w-4/5 bg-transparent outline-none'
              placeholder='buscar produto...'
            />
          </label>
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
